### ISSUE TITLE
Failing on task detect mysql ido version on second run

### ISSUE THREAD

**Issue by ekartsonakis** [bodsch/ansible-icinga2#59]
##### SUMMARY
After the first run, when `create the mysql ido schema` successfully created ido DB schema, if we run again the role it is failing on task: `detect mysql ido version` with error. 

##### STEPS TO REPRODUCE

```yaml
Re-run the role on the same host
```

##### EXPECTED RESULTS

```paste below
Detect mysql ido version and register the value for the next task
```

##### ACTUAL RESULTS

```paste below
TASK [ansible-icinga2 : detect mysql ido version] **************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: too many values to unpack (expected 2)
fatal: [f6t-mon-001]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 107, in <module>
      File "<stdin>", line 99, in _ansiballz_main
      File "<stdin>", line 47, in invoke_module
      File "/usr/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_icinga2_ido_version_payload_5ot7egot/ansible_icinga2_ido_version_payload.zip/ansible/modules/icinga2_ido_version.py", line 204, in <module>
      File "/tmp/ansible_icinga2_ido_version_payload_5ot7egot/ansible_icinga2_ido_version_payload.zip/ansible/modules/icinga2_ido_version.py", line 195, in main
      File "/tmp/ansible_icinga2_ido_version_payload_5ot7egot/ansible_icinga2_ido_version_payload.zip/ansible/modules/icinga2_ido_version.py", line 72, in run
    ValueError: too many values to unpack (expected 2)
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

##### ENVIRONMENT

**ansible host**: ansible [core 2.13.5]
**target host OS**: Debian 11.5
**target host installed ido utils version**: 1.15.1
**target host installed MariaDB version**: 10.6.11

**Comment by bodsch** [comment]
Good morning!

Unfortunately I can't reproduce the problem!

My first run (with ansible parameter `-v`) gives this output:

```
TASK [ansible-icinga2 : detect mysql ido version] ******************************
Dienstag 29 November 2022  05:20:23 +0100 (0:00:01.827)       0:01:57.659 *****
ok: [instance] => changed=false 
  exists: false
  ido_version: 0
```
The output in the journal:
```
Nov 29 04:20:24 instance ansible-icinga2_ido_version[16087]: Invoked with dba_host=database dba_user=********_ido dba_password=NOT_LOGGING_PARAMETER dba_database=********_ido dba_port=3306 database_config_file=None
Nov 29 04:20:24 instance ansible-icinga2_ido_version[16087]: = result: {'failed': False, 'exists': False, 'ido_version': 0}
```

And all further runs this:
```
TASK [ansible-icinga2 : detect mysql ido version] ******************************
Dienstag 29 November 2022  05:23:50 +0100 (0:00:01.865)       0:01:04.751 *****
ok: [instance] => changed=false 
  exists: true
  ido_version: 1.15.1
```

The output in the journal:
```
Nov 29 04:23:51 instance ansible-icinga2_ido_version[24380]: Invoked with dba_host=database dba_user=********_ido dba_password=NOT_LOGGING_PARAMETER dba_database=********_ido dba_port=3306 database_config_file=None
Nov 29 04:23:51 instance ansible-icinga2_ido_version[24380]: = result: {'failed': False, 'exists': True, 'ido_version': '1.15.1'}
```

Could you please give me an excerpt from the log file of the icinga instance:
`journalctl | grep ansible-icinga2_ido`

**Comment by ekartsonakis** [comment]
Hi,
Thanks for quick reply!
It has obviously something to do with the DB access. Although we see that ido user specified in the vars section has full access to `icinga2_ido` DB. Switched to `no_log: false` in **icinga2_ido_version.py** to ensure the correct credentials are used.
```
Nov 30 14:47:11 f6t-mon-001 ansible-icinga2_ido_version[174538]: Invoked with dba_host=localhost dba_user=icinga2_ido dba_password=icinga2_ido dba_database=icinga2_ido dba_port=3306 database_config_file=None
Nov 30 14:47:11 f6t-mon-001 ansible-icinga2_ido_version[174538]: unable to connect to database. check login_host, login_user and login_password are correct or None has the credentials. Exception message: (1045, "Access denied for user 'icinga2_ido'@'localhost' (using password: YES)")
```

but when trying the same from command line with the same ido user credentials it works:
```
f6t-mon-001 ~ % mysql -u icinga2_ido -picinga2_ido -h localhost icinga2_ido  
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 297
Server version: 10.6.11-MariaDB-1:10.6.11+maria~deb11-log mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [icinga2_ido]> select * from `icinga2_ido`.`icinga_dbversion`;
+--------------+----------+---------+---------------------+---------------------+
| dbversion_id | name     | version | create_time         | modify_time         |
+--------------+----------+---------+---------------------+---------------------+
|            1 | idoutils | 1.15.1  | 2022-11-28 12:42:04 | 2022-11-28 12:42:04 |
+--------------+----------+---------+---------------------+---------------------+
1 row in set (0.000 sec)

```

Here is the vars in the playbook:
```
     icinga2_ido:
       user: icinga2_ido
       password: icinga2_ido
       host: localhost
       database: icinga2_ido
```
Maybe it is a MariaDB issue/bug when connecting to localhost which is what we are currently investigating.

One more question:
In case we want all satellites and master node to have ansible controlled config files. Do we really need IDO feature or it is only useful in case we want config to be managed though Icinga Web?

Thank you!

**Comment by ekartsonakis** [comment]
Indeed it was a MariaDB issue. We explicitly added host as `127.0.0.1` instead of `localhost` and it worked (!!) . See: https://stackoverflow.com/questions/47242111/mysql-able-to-connect-to-localhost-but-not-to-127-0-0-1

**Comment by bodsch** [comment]
> One more question:
> In case we want all satellites and master node to have ansible controlled config files. Do we really need IDO feature or it is only useful in case we want config to be managed though Icinga Web?

IDO is only needed for the Primary.
The feature is not enabled for satellites.
And yes, IDO is still needed. If you plan to use IcingaDB, it will take over most of the data management and the DBA will only be needed for persistent data management.
I recommend the use of IcingaDB.

> Indeed it was a MariaDB issue. We explicitly added host as `127.0.0.1` instead of `localhost` and it worked (!!) . See: https://stackoverflow.com/questions/47242111/mysql-able-to-connect-to-localhost-but-not-to-127-0-0-1

Oh. Thank you for the feedback!
Since I always roll out the database separately in my test setup, I haven't noticed this before. :}

**Comment by ekartsonakis** [comment]
Thank you for the context and your work in this role! Closing this issue.
